# Generated by Django 3.1.4 on 2021-05-16 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210516_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductViewerFavorRecord',
            new_name='ProductViewerRecord',
        ),
        migrations.RemoveField(
            model_name='productcommentfavorrecord',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='productcommentfavorrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productcommentrecord',
            name='favor_count',
        ),
        migrations.AlterField(
            model_name='productcollectrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinforecord', verbose_name='商品'),
        ),
        migrations.DeleteModel(
            name='ProductCollectFavorRecord',
        ),
        migrations.DeleteModel(
            name='ProductCommentFavorRecord',
        ),
    ]
