# Generated by Django 3.1.4 on 2021-05-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210516_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealInfoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.PositiveIntegerField(default=0, verbose_name='完成情况')),
                ('agreement', models.PositiveIntegerField(default=0, verbose_name='是否同意')),
                ('datatime', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('finish_time', models.DateTimeField(auto_now=True, verbose_name='完成交易时间')),
                ('address', models.CharField(max_length=32, verbose_name='交易地点')),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_product', to='api.productinforecord', verbose_name='被交易物品')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_product', to='api.productinforecord', verbose_name='交易物品')),
            ],
        ),
    ]
