# Generated by Django 3.1.4 on 2021-05-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dealinforecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinforecord',
            name='bool_deal',
            field=models.PositiveIntegerField(default=0, verbose_name='交易状态'),
        ),
    ]
