# Generated by Django 3.1.4 on 2021-06-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productinforecord_bool_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcommentrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productinforecord', verbose_name='商品'),
        ),
    ]
