# Generated by Django 3.1.4 on 2021-06-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210609_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(default='大连', max_length=16, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.PositiveIntegerField(default=1, verbose_name='性别'),
        ),
    ]
